import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "dewi",
      email: "dewi@smkn12malang.sch.id",
      password: bcrypt.hashSync("haveagoodlife", 8),
      isAdmin: true,
    },
    // {
    // name: "John",
    //email: "john@example.com",
    //password: bcrypt.hashSync("12345", 8),
    // isAdmin: false,
    //},
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120000,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "High Quality Products",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 320000,
      countInStock: 30,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 1329,
      description: "High Quality Products",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120080,
      countInStock: 432,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 27,
      description: "High Quality Products",
    },
    {
      name: "Nike Slim Pent",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 431000,
      countInStock: 1990,
      brand: "Nike",
      rating: 4.5,
      numReviews: 90,
      description: "High Quality Products",
    },
    {
      name: "Puma Fit Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 120000,
      countInStock: 10,
      brand: "Puma",
      rating: 3.7,
      numReviews: 106,
      description: "High Quality Products",
    },
    {
      name: "Adidas Fit Pants",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 109000,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 90,
      description: "High Quality Products",
    },
  ],
};
export default data;
